from typing import List
from ._formula import Formula

class Calculator:
    def __init__(self) -> None:
        self.rtol: float = ...
        self.charge: int = ...
    
    def __setitem__(self, e:str, num:int):...
    def __getitem__(self, e:str)->int:...
    def getEIList(self)->List[str]:...
    def get(self, M:float)->List[Formula]:...