# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Orbitool\UI\CalibrationDetail.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(797, 551)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.segmentsListWidget = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segmentsListWidget.sizePolicy().hasHeightForWidth())
        self.segmentsListWidget.setSizePolicy(sizePolicy)
        self.segmentsListWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.segmentsListWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.segmentsListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.segmentsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.segmentsListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.segmentsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.segmentsListWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.segmentsListWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.segmentsListWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.segmentsListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.segmentsListWidget.setObjectName("segmentsListWidget")
        self.horizontalLayout_2.addWidget(self.segmentsListWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.calibrationSplitter = QtWidgets.QSplitter(Form)
        self.calibrationSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.calibrationSplitter.setOpaqueResize(True)
        self.calibrationSplitter.setHandleWidth(5)
        self.calibrationSplitter.setObjectName("calibrationSplitter")
        self.layoutWidget = QtWidgets.QWidget(self.calibrationSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spectraTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectraTableWidget.sizePolicy().hasHeightForWidth())
        self.spectraTableWidget.setSizePolicy(sizePolicy)
        self.spectraTableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.spectraTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.spectraTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.spectraTableWidget.setObjectName("spectraTableWidget")
        self.spectraTableWidget.setColumnCount(1)
        self.spectraTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.spectraTableWidget.setHorizontalHeaderItem(0, item)
        self.spectraTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.spectraTableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.spectrumIonsTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrumIonsTableWidget.sizePolicy().hasHeightForWidth())
        self.spectrumIonsTableWidget.setSizePolicy(sizePolicy)
        self.spectrumIonsTableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.spectrumIonsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.spectrumIonsTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.spectrumIonsTableWidget.setObjectName("spectrumIonsTableWidget")
        self.spectrumIonsTableWidget.setColumnCount(3)
        self.spectrumIonsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumIonsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumIonsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumIonsTableWidget.setHorizontalHeaderItem(2, item)
        self.spectrumIonsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.spectrumIonsTableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.spectrumPlotWidget = QtWidgets.QWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrumPlotWidget.sizePolicy().hasHeightForWidth())
        self.spectrumPlotWidget.setSizePolicy(sizePolicy)
        self.spectrumPlotWidget.setObjectName("spectrumPlotWidget")
        self.verticalLayout_4.addWidget(self.spectrumPlotWidget)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.calibrationSplitter)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.filesTableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesTableWidget.sizePolicy().hasHeightForWidth())
        self.filesTableWidget.setSizePolicy(sizePolicy)
        self.filesTableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.filesTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.filesTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.filesTableWidget.setObjectName("filesTableWidget")
        self.filesTableWidget.setColumnCount(2)
        self.filesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesTableWidget.setHorizontalHeaderItem(1, item)
        self.filesTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.filesTableWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.fileIonsTableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileIonsTableWidget.sizePolicy().hasHeightForWidth())
        self.fileIonsTableWidget.setSizePolicy(sizePolicy)
        self.fileIonsTableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.fileIonsTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.fileIonsTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.fileIonsTableWidget.setObjectName("fileIonsTableWidget")
        self.fileIonsTableWidget.setColumnCount(4)
        self.fileIonsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fileIonsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileIonsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileIonsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fileIonsTableWidget.setHorizontalHeaderItem(3, item)
        self.fileIonsTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.fileIonsTableWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.filePlotWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePlotWidget.sizePolicy().hasHeightForWidth())
        self.filePlotWidget.setSizePolicy(sizePolicy)
        self.filePlotWidget.setObjectName("filePlotWidget")
        self.verticalLayout_5.addWidget(self.filePlotWidget)
        self.verticalLayout.addWidget(self.calibrationSplitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calibration Detail"))
        self.label.setText(_translate("Form", "Segments"))
        self.label_2.setText(_translate("Form", "Spectra List"))
        item = self.spectraTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "time range"))
        self.label_4.setText(_translate("Form", "Ions"))
        item = self.spectrumIonsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "mz"))
        item = self.spectrumIonsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "rtol"))
        item = self.spectrumIonsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "intensity"))
        self.label_3.setText(_translate("Form", "File List"))
        item = self.filesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "create time"))
        item = self.filesTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "path"))
        self.label_5.setText(_translate("Form", "Ions"))
        item = self.fileIonsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "theoretic mz"))
        item = self.fileIonsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "mz"))
        item = self.fileIonsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "rtol(ppm)"))
        item = self.fileIonsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "use for calibration"))

