# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Orbitool\UI\FormulaResult.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.calcPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcPushButton.setObjectName("calcPushButton")
        self.horizontalLayout_4.addWidget(self.calcPushButton)
        self.forceCalcPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.forceCalcPushButton.setObjectName("forceCalcPushButton")
        self.horizontalLayout_4.addWidget(self.forceCalcPushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.resultTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.resultTableWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.resultTableWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.resultTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.resultTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(4)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resultTableWidget.setHorizontalHeaderItem(3, item)
        self.resultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.resultTableWidget)
        self.isotopesTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.isotopesTableWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.isotopesTableWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.isotopesTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.isotopesTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.isotopesTableWidget.setObjectName("isotopesTableWidget")
        self.isotopesTableWidget.setColumnCount(6)
        self.isotopesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesTableWidget.setHorizontalHeaderItem(5, item)
        self.isotopesTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.isotopesTableWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.showAllToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.showAllToolButton.setObjectName("showAllToolButton")
        self.horizontalLayout_3.addWidget(self.showAllToolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.acceptEmptyToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.acceptEmptyToolButton.setObjectName("acceptEmptyToolButton")
        self.horizontalLayout_2.addWidget(self.acceptEmptyToolButton)
        self.acceptToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.acceptToolButton.setObjectName("acceptToolButton")
        self.horizontalLayout_2.addWidget(self.acceptToolButton)
        self.closeToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.closeToolButton.setObjectName("closeToolButton")
        self.horizontalLayout_2.addWidget(self.closeToolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Formula Calculation Result"))
        self.calcPushButton.setText(_translate("MainWindow", "Calc"))
        self.forceCalcPushButton.setText(_translate("MainWindow", "Unrestricted Calc"))
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "formula"))
        item = self.resultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "mass"))
        item = self.resultTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "tolerance(ppm)"))
        item = self.resultTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "unsaturation"))
        item = self.isotopesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "formula"))
        item = self.isotopesTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "mass"))
        item = self.isotopesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "tolerance(ppm)"))
        item = self.isotopesTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "abundance"))
        item = self.isotopesTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "actual intensity"))
        item = self.isotopesTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "actual ratio"))
        self.showAllToolButton.setText(_translate("MainWindow", "show all"))
        self.acceptEmptyToolButton.setText(_translate("MainWindow", "Accept empty list"))
        self.acceptToolButton.setText(_translate("MainWindow", "Accept"))
        self.closeToolButton.setText(_translate("MainWindow", "Close"))

