# Form implementation generated from reading ui file 'Orbitool\UI\Main.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.processWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.processWidget.setObjectName("processWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.processWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBarLayout = QtWidgets.QVBoxLayout()
        self.progressBarLayout.setObjectName("progressBarLayout")
        self.horizontalLayout_2.addLayout(self.progressBarLayout)
        self.abortPushButton = QtWidgets.QPushButton(parent=self.processWidget)
        self.abortPushButton.setObjectName("abortPushButton")
        self.horizontalLayout_2.addWidget(self.abortPushButton)
        self.verticalLayout.addWidget(self.processWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuWorkspace = QtWidgets.QMenu(parent=self.menubar)
        self.menuWorkspace.setObjectName("menuWorkspace")
        self.menuOrbitool = QtWidgets.QMenu(parent=self.menubar)
        self.menuOrbitool.setObjectName("menuOrbitool")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.workspaceSaveAction = QtGui.QAction(parent=MainWindow)
        self.workspaceSaveAction.setObjectName("workspaceSaveAction")
        self.workspaceLoadAction = QtGui.QAction(parent=MainWindow)
        self.workspaceLoadAction.setObjectName("workspaceLoadAction")
        self.workspaceSaveAsAction = QtGui.QAction(parent=MainWindow)
        self.workspaceSaveAsAction.setObjectName("workspaceSaveAsAction")
        self.configLoadAction = QtGui.QAction(parent=MainWindow)
        self.configLoadAction.setObjectName("configLoadAction")
        self.configSaveAction = QtGui.QAction(parent=MainWindow)
        self.configSaveAction.setObjectName("configSaveAction")
        self.actionss = QtGui.QAction(parent=MainWindow)
        self.actionss.setObjectName("actionss")
        self.settingAction = QtGui.QAction(parent=MainWindow)
        self.settingAction.setObjectName("settingAction")
        self.menuWorkspace.addAction(self.workspaceLoadAction)
        self.menuWorkspace.addAction(self.workspaceSaveAction)
        self.menuWorkspace.addAction(self.workspaceSaveAsAction)
        self.menuWorkspace.addSeparator()
        self.menuWorkspace.addAction(self.configLoadAction)
        self.menuWorkspace.addAction(self.configSaveAction)
        self.menuOrbitool.addAction(self.settingAction)
        self.menubar.addAction(self.menuWorkspace.menuAction())
        self.menubar.addAction(self.menuOrbitool.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.abortPushButton.setText(_translate("MainWindow", "Abort"))
        self.menuWorkspace.setTitle(_translate("MainWindow", "Workspace"))
        self.menuOrbitool.setTitle(_translate("MainWindow", "Orbitool"))
        self.workspaceSaveAction.setText(_translate("MainWindow", "Save"))
        self.workspaceSaveAction.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.workspaceLoadAction.setText(_translate("MainWindow", "Load"))
        self.workspaceSaveAsAction.setText(_translate("MainWindow", "Save as"))
        self.configLoadAction.setText(_translate("MainWindow", "Load config from workspace"))
        self.configLoadAction.setToolTip(_translate("MainWindow", "Load Config from Workspace"))
        self.configSaveAction.setText(_translate("MainWindow", "Save config to workspace"))
        self.configSaveAction.setToolTip(_translate("MainWindow", "Save Config to Workspace"))
        self.actionss.setText(_translate("MainWindow", "ss"))
        self.settingAction.setText(_translate("MainWindow", "Setting"))
