# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Orbitool\UI\PeakFitFloat.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(677, 354)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.isotopeWidget = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isotopeWidget.sizePolicy().hasHeightForWidth())
        self.isotopeWidget.setSizePolicy(sizePolicy)
        self.isotopeWidget.setObjectName("isotopeWidget")
        self.verticalLayout_3.addWidget(self.isotopeWidget)
        self.isotopesPropertyTableWidget = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isotopesPropertyTableWidget.sizePolicy().hasHeightForWidth())
        self.isotopesPropertyTableWidget.setSizePolicy(sizePolicy)
        self.isotopesPropertyTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.isotopesPropertyTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.isotopesPropertyTableWidget.setObjectName("isotopesPropertyTableWidget")
        self.isotopesPropertyTableWidget.setColumnCount(6)
        self.isotopesPropertyTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesPropertyTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesPropertyTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesPropertyTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesPropertyTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesPropertyTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.isotopesPropertyTableWidget.setHorizontalHeaderItem(5, item)
        self.isotopesPropertyTableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.isotopesPropertyTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.isotopesPropertyTableWidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        self.originCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.originCheckBox.setChecked(True)
        self.originCheckBox.setObjectName("originCheckBox")
        self.horizontalLayout_10.addWidget(self.originCheckBox)
        self.sumCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.sumCheckBox.setChecked(True)
        self.sumCheckBox.setObjectName("sumCheckBox")
        self.horizontalLayout_10.addWidget(self.sumCheckBox)
        self.residualCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.residualCheckBox.setChecked(True)
        self.residualCheckBox.setObjectName("residualCheckBox")
        self.horizontalLayout_10.addWidget(self.residualCheckBox)
        self.legendCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.legendCheckBox.setChecked(True)
        self.legendCheckBox.setObjectName("legendCheckBox")
        self.horizontalLayout_10.addWidget(self.legendCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.peakWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakWidget.sizePolicy().hasHeightForWidth())
        self.peakWidget.setSizePolicy(sizePolicy)
        self.peakWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.peakWidget.setObjectName("peakWidget")
        self.verticalLayout.addWidget(self.peakWidget)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.peakTableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peakTableWidget.sizePolicy().hasHeightForWidth())
        self.peakTableWidget.setSizePolicy(sizePolicy)
        self.peakTableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.peakTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.peakTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.peakTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.peakTableWidget.setObjectName("peakTableWidget")
        self.peakTableWidget.setColumnCount(2)
        self.peakTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.peakTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peakTableWidget.setHorizontalHeaderItem(1, item)
        self.peakTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.peakTableWidget)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.numSpinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numSpinBox.sizePolicy().hasHeightForWidth())
        self.numSpinBox.setSizePolicy(sizePolicy)
        self.numSpinBox.setMinimum(1)
        self.numSpinBox.setMaximum(20)
        self.numSpinBox.setObjectName("numSpinBox")
        self.horizontalLayout_15.addWidget(self.numSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.refitPushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refitPushButton.sizePolicy().hasHeightForWidth())
        self.refitPushButton.setSizePolicy(sizePolicy)
        self.refitPushButton.setObjectName("refitPushButton")
        self.verticalLayout_4.addWidget(self.refitPushButton)
        self.horizontalLayout_12.addLayout(self.verticalLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.peaksPropertyTableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peaksPropertyTableWidget.sizePolicy().hasHeightForWidth())
        self.peaksPropertyTableWidget.setSizePolicy(sizePolicy)
        self.peaksPropertyTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.peaksPropertyTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.peaksPropertyTableWidget.setObjectName("peaksPropertyTableWidget")
        self.peaksPropertyTableWidget.setColumnCount(6)
        self.peaksPropertyTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.peaksPropertyTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.peaksPropertyTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.peaksPropertyTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.peaksPropertyTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.peaksPropertyTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.peaksPropertyTableWidget.setHorizontalHeaderItem(5, item)
        self.peaksPropertyTableWidget.horizontalHeader().setDefaultSectionSize(70)
        self.peaksPropertyTableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_5.addWidget(self.peaksPropertyTableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closePushButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closePushButton.sizePolicy().hasHeightForWidth())
        self.closePushButton.setSizePolicy(sizePolicy)
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout.addWidget(self.closePushButton)
        self.savePushButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePushButton.sizePolicy().hasHeightForWidth())
        self.savePushButton.setSizePolicy(sizePolicy)
        self.savePushButton.setObjectName("savePushButton")
        self.horizontalLayout.addWidget(self.savePushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_12.addLayout(self.verticalLayout_19)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Isotope peaks"))
        item = self.isotopesPropertyTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "formula"))
        item = self.isotopesPropertyTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "position"))
        item = self.isotopesPropertyTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "intensity"))
        item = self.isotopesPropertyTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ppm"))
        item = self.isotopesPropertyTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "isotope ratio"))
        item = self.isotopesPropertyTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ref ratio"))
        self.label_18.setText(_translate("Form", "show"))
        self.originCheckBox.setText(_translate("Form", "origin"))
        self.sumCheckBox.setText(_translate("Form", "sum"))
        self.residualCheckBox.setText(_translate("Form", "residual"))
        self.legendCheckBox.setText(_translate("Form", "legend"))
        item = self.peakTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "mz"))
        item = self.peakTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "intensity"))
        self.label_13.setText(_translate("Form", "peak num"))
        self.refitPushButton.setText(_translate("Form", "Re-fit"))
        self.groupBox_2.setTitle(_translate("Form", "Peaks"))
        item = self.peaksPropertyTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "formula"))
        item = self.peaksPropertyTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "position"))
        item = self.peaksPropertyTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "intensity"))
        item = self.peaksPropertyTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ppm"))
        item = self.peaksPropertyTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "isotope ratio"))
        item = self.peaksPropertyTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ref ratio"))
        self.closePushButton.setText(_translate("Form", "Close"))
        self.savePushButton.setText(_translate("Form", "Save"))

