# Form implementation generated from reading ui file 'Orbitool\UI\Timeseries.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(289, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.retentionTimeCheckBox = QtWidgets.QCheckBox(parent=Form)
        self.retentionTimeCheckBox.setObjectName("retentionTimeCheckBox")
        self.verticalLayout.addWidget(self.retentionTimeCheckBox)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.exportPushButton = QtWidgets.QPushButton(parent=Form)
        self.exportPushButton.setObjectName("exportPushButton")
        self.verticalLayout.addWidget(self.exportPushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.retentionTimeCheckBox.setText(_translate("Form", "use retention time"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "intensity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "position"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "deviation(ppm)"))
        self.exportPushButton.setText(_translate("Form", "Export this time series"))
