# Form implementation generated from reading ui file 'Orbitool\UI\setting\DenoiseTab.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 511)
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.peaksLabel = QtWidgets.QLabel(parent=Form)
        self.peaksLabel.setToolTip("")
        self.peaksLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.peaksLabel.setObjectName("peaksLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.peaksLabel)
        self.peaksPlainTextEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.peaksPlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.peaksPlainTextEdit.setObjectName("peaksPlainTextEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.peaksPlainTextEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.noiseDifferentColorCheckBox = QtWidgets.QCheckBox(parent=Form)
        self.noiseDifferentColorCheckBox.setText("")
        self.noiseDifferentColorCheckBox.setObjectName("noiseDifferentColorCheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.noiseDifferentColorCheckBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.peaksLabel.setText(_translate("Form", "High-intensity peaks\n"
"initial list"))
        self.label.setText(_translate("Form", "Plot noise in different color"))
