# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Orbitool\UI\setting\FileTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 511)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.dotnetDriverLabel = QtWidgets.QLabel(Form)
        self.dotnetDriverLabel.setObjectName("dotnetDriverLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dotnetDriverLabel)
        self.dotnetDriverComboBox = QtWidgets.QComboBox(Form)
        self.dotnetDriverComboBox.setObjectName("dotnetDriverComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dotnetDriverComboBox)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dotnetDriverLabel.setToolTip(_translate("Form", "use first spectrum if nothing is selected"))
        self.dotnetDriverLabel.setText(_translate("Form", ".Net driver"))
        self.label.setText(_translate("Form", "Takes effect after reopening.\n"
"Avoid non-ASCII chars in program and file paths"))
