# Form implementation generated from reading ui file 'Orbitool\UI\setting\FileTab.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 511)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.dotnetDriverLabel = QtWidgets.QLabel(parent=Form)
        self.dotnetDriverLabel.setToolTip("")
        self.dotnetDriverLabel.setObjectName("dotnetDriverLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dotnetDriverLabel)
        self.dotnetDriverComboBox = QtWidgets.QComboBox(parent=Form)
        self.dotnetDriverComboBox.setObjectName("dotnetDriverComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dotnetDriverComboBox)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dotnetDriverLabel.setText(_translate("Form", ".Net driver"))
        self.label.setText(_translate("Form", "Takes effect after reopening.\n"
"Avoid non-ASCII chars in program and file paths"))
