# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Orbitool\UI\setting\GeneralTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 511)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.defaultSelectLabel = QtWidgets.QLabel(Form)
        self.defaultSelectLabel.setObjectName("defaultSelectLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.defaultSelectLabel)
        self.defaultSelectCheckBox = QtWidgets.QCheckBox(Form)
        self.defaultSelectCheckBox.setText("")
        self.defaultSelectCheckBox.setObjectName("defaultSelectCheckBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.defaultSelectCheckBox)
        self.timeFormatLabel = QtWidgets.QLabel(Form)
        self.timeFormatLabel.setObjectName("timeFormatLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.timeFormatLabel)
        self.timeFormatLineEdit = QtWidgets.QLineEdit(Form)
        self.timeFormatLineEdit.setObjectName("timeFormatLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.timeFormatLineEdit)
        self.exportTimeFormatLabel = QtWidgets.QLabel(Form)
        self.exportTimeFormatLabel.setObjectName("exportTimeFormatLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.exportTimeFormatLabel)
        self.exportTimeFormatLineEdit = QtWidgets.QLineEdit(Form)
        self.exportTimeFormatLineEdit.setObjectName("exportTimeFormatLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.exportTimeFormatLineEdit)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.multiCoresSpinBox = QtWidgets.QSpinBox(Form)
        self.multiCoresSpinBox.setObjectName("multiCoresSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.multiCoresSpinBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeFormatShowLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.timeFormatShowLabel.setFont(font)
        self.timeFormatShowLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeFormatShowLabel.setObjectName("timeFormatShowLabel")
        self.horizontalLayout.addWidget(self.timeFormatShowLabel)
        self.timeFormatRevertButton = QtWidgets.QToolButton(Form)
        self.timeFormatRevertButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.timeFormatRevertButton.setFont(font)
        self.timeFormatRevertButton.setObjectName("timeFormatRevertButton")
        self.horizontalLayout.addWidget(self.timeFormatRevertButton)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportTimeFormatShowLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exportTimeFormatShowLabel.setFont(font)
        self.exportTimeFormatShowLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exportTimeFormatShowLabel.setObjectName("exportTimeFormatShowLabel")
        self.horizontalLayout_2.addWidget(self.exportTimeFormatShowLabel)
        self.exportTimeFormatRevertButton = QtWidgets.QToolButton(Form)
        self.exportTimeFormatRevertButton.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.exportTimeFormatRevertButton.setFont(font)
        self.exportTimeFormatRevertButton.setObjectName("exportTimeFormatRevertButton")
        self.horizontalLayout_2.addWidget(self.exportTimeFormatRevertButton)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.defaultSelectLabel.setToolTip(_translate("Form", "use first spectrum if nothing is selected"))
        self.defaultSelectLabel.setText(_translate("Form", "default select"))
        self.timeFormatLabel.setText(_translate("Form", "shown time format"))
        self.exportTimeFormatLabel.setText(_translate("Form", "export filename time format"))
        self.label.setText(_translate("Form", "use cpu cores"))
        self.timeFormatShowLabel.setText(_translate("Form", "TextLabel"))
        self.timeFormatRevertButton.setText(_translate("Form", "revert"))
        self.exportTimeFormatShowLabel.setText(_translate("Form", "TextLabel"))
        self.exportTimeFormatRevertButton.setText(_translate("Form", "revert"))
