# Form implementation generated from reading ui file 'Orbitool\UI\setting\TimeseriesTab.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(335, 511)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.timeformatLabel = QtWidgets.QLabel(parent=Form)
        self.timeformatLabel.setObjectName("timeformatLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.timeformatLabel)
        self.timeformatVerticalLayout = QtWidgets.QVBoxLayout()
        self.timeformatVerticalLayout.setObjectName("timeformatVerticalLayout")
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.timeformatVerticalLayout)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.mzRangeTargetComboBox = QtWidgets.QComboBox(parent=Form)
        self.mzRangeTargetComboBox.setObjectName("mzRangeTargetComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.mzRangeTargetComboBox)
        self.mzRangePeakfitFuncCommboBox = QtWidgets.QComboBox(parent=Form)
        self.mzRangePeakfitFuncCommboBox.setObjectName("mzRangePeakfitFuncCommboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.mzRangePeakfitFuncCommboBox)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.timeformatLabel.setText(_translate("Form", "export time formats"))
        self.label.setText(_translate("Form", "mz range sum target"))
        self.label_2.setText(_translate("Form", "mz range sum peakfit func"))
